// <auto-generated />
namespace GoogleSignIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class insertdefaultvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insertdefaultvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "202002040645567_insert default values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
